### ISSUE TITLE
JSONClasses 需要Python 3.10。如果您没有安装它，您可以按照此处的下载指南进行操作 。

### ISSUE THREAD

**Issue by Chanli52580** [fillmula/jsonclasses#36]
Python3.7 不支持吗 
Windows操作系统
pip install  jsonclasses-server
ERROR: Could not find a version that satisfies the requirement jsonclasses-server (from versions: none)
ERROR: No matching distribution found for jsonclasses-server

**Comment by victorteokw** [comment]
Please do not write issues in languages other than English.
Python <3.10 is not supported.

**Comment by Chanli52580** [comment]
> Please do not write issues in languages other than English. Python <3.10 is not supported.

NiuBi
