### ISSUE TITLE
Mapping model support

### ISSUE THREAD

**Issue by ViktorSky** [fillmula/jsonclasses#41]
How to create a mapping model? It is necessary in the event that the data does not have specific keys

The example data is:
```py
{
    '66049558-e3ac-4386-9430-27fb5545beab': {'name': 'John', 'age': 25},
    'fdb1dbef-fdcd-488d-ad92-f861003f7093': {'name': 'Max', 'age': 23}
}
```

If it can't be done, will it be added in later versions of the library?

**Comment by AlanBogarin** [comment]
?

**Comment by victorteokw** [comment]
we don't support this
